var facilities=Vue.extend({
	template:'#facilities',
	data:function(){
		return{
			items:[],
			facItem:{
				fac_tolit:[],
				fac_elec:[],
				fac_ss:[],
				fac_require:[]
			}
		};
	},
	created:function(){
		this.items=[
			{
				name:'卫浴',
				class:'tolit',
				options:[
					{name:'牙具',value:'牙具'},
					{name:'香皂',value:'香皂'},
					{name:'毛巾',value:'毛巾'},
					{name:'浴液 洗发水',value:'浴液 洗发水'},
					{name:'手纸',value:'手纸'},
					{name:'热水淋浴',value:'热水淋浴'},
					{name:'浴缸',value:'浴缸'},
					{name:'拖鞋',value:'拖鞋'}
				]
			},
			{
				name:'电器',
				class:'elec',
				options:[
					{name:'电视',value:'电视'},
					{name:'空调',value:'空调'},
					{name:'饮水设备',value:'饮水设备'},
					{name:'冰箱',value:'冰箱'},
					{name:'洗衣机',value:'洗衣机'}
				]
			},
			{
				name:'设施',
				class:'ss',
				options:[
					{name:'WiFi',value:'WiFi'},
					{name:'有线网络',value:'有线网络'},
					{name:'暖气',value:'暖气'},
					{name:'电梯',value:'电梯'},
					{name:'门禁系统',value:'门禁系统'},
					{name:'停车位',value:'停车位'}
				]
			},
			{
				name:'要求',
				class:'require',
				options:[
					{name:'允许吸烟',value:'允许吸烟'},
					{name:'允许做饭',value:'允许做饭'},
					{name:'允许带宠物',value:'允许带宠物'},
					{name:'允许聚会',value:'允许聚会'}
				]
			}
		]
	},
	methods:{
		deepCopy:function(obj1,obj2){
			for(var p in obj1){
				if(Array.isArray(obj1[p]))
					obj2[p]=obj1[p].slice(0);
				else if(obj1[p]!=null&&(typeof obj1[p]=='object')){
					obj2[p]={};
					arguments.callee(obj1[p],obj2[p]);
				}else
					obj2[p]=obj1[p];
			}
		},
		saveComplete:function(){
			if(!confirm('确认保存并进行下一步?')) return;
			this.$emit('save-complete');
			// this.$store.state.tab.curIndex=this.index+1;
			this.$http({
				url:this.$store.state.tab.url+'information/add/',
				method:"POST",
				data:JSON.stringify(this.facItem)
			}).then(function(res){});
		}
	}
});
Vue.component('myfacilities',facilities);